version: '3.8'

services:
  mysql-docker-container:
    image: mysql:8.0.30
    environment:
      - MYSQL_DATABASE=jwtapp
      - MYSQL_ROOT_PASSWORD=vasylkit
    ports:
      - '3307:3306'

  app:
    build: ./
    container_name: 'rest-api'
    ports:
      - "8070:8070"